import React, { useState } from "react";
import { askAI } from "./ai";
import { useNavigate } from "react-router-dom";
export default function AIChat({ wrongAnswers, onClose }) {
  const [response, setResponse] = useState("");
  const [loading, setLoading] = useState(false);


const navigate = useNavigate();




  const handleReveal = async () => {
    console.log(wrongAnswers)
    navigate("/ai-chat", { state: { wrongAnswers } });
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/90 text-white flex items-center justify-center p-6">
      <div className="relative w-full max-w-xl p-6 bg-white/10 backdrop-blur-xl border border-white/20 rounded-2xl shadow-lg">
        
        <h2 className="text-xl font-bold mb-4">AI Reveal Answers ⚡</h2>
        <p className="text-sm text-gray-300 mb-4">
          These answers are generated by AI. <br />
          ⚠️ Caution: AI may make mistakes, please cross-check with the Bible.
        </p>

        {/* Show Wrong Qs for clarity */}
        <div className="space-y-2 mb-4">
          {Object.entries(wrongAnswers)
  .map(([question, answer]) => `❓ ${question}\n✅ Correct: ${answer}`)
  .join("\n\n")

}
        </div>

        {/* Button → fetch AI answer */}
        {!response && !loading && (
          <button
        onClick={handleReveal}
        className="mt-4 px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-500"
      >
        Reveal Answer with AI
      </button>

        )}

        {/* Loading state */}
        {loading && <p className="animate-pulse text-gray-400">AI is thinking…</p>}

        {/* Response */}
        {response && (
          <div className="mt-4 p-4 rounded-lg bg-white/5 border border-white/10 text-sm">
            {response}
          </div>
        )}

        {/* Close */}
        <button
          onClick={onClose}
          className="mt-4 px-4 py-2 rounded-lg bg-red-600 hover:bg-red-700 transition w-full"
        >
          Close
        </button>
      </div>
    </div>
  );
}
